# https://github.com/users/A1exL/packages/container/ci-cd-test/settings - Danger Zone -> Change package visibility
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
# https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images
name: CI CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: maven
    
    - name: Build with Maven
      run: mvn -B clean package

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: ls -la
      run: ls -la

#    - name: Docker build and push
#      run: docker build --push -t ghcr.io/a1exl/ci-cd-test:x${{ github.run_number }} .


